# Generated by Django 2.1.5 on 2019-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='서브웨이', max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('introduction', models.TextField(default='설명 없음')),
                ('category', models.CharField(choices=[('DR', '샌드위치'), ('TP', '토핑'), ('SM', '사이드'), ('DR', '음료')], default='SW', max_length=2)),
            ],
        ),
    ]
